"""Initial migration

Revision ID: d2046e6629c4
Revises: 
Create Date: 2024-03-12 18:31:47.616068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2046e6629c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roleName', sa.String(), nullable=False),
    sa.Column('stageCurrent', sa.Integer(), nullable=False),
    sa.Column('nextStage', sa.Integer(), nullable=False),
    sa.Column('prevStage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('emailId', sa.String(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('payLevel', sa.Integer(), nullable=False),
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('dateOfJoining', sa.DateTime(), nullable=False),
    sa.Column('standingEarnedLeave', sa.Integer(), nullable=True),
    sa.Column('signUrl', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ltc_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('fromDate', sa.DateTime(), nullable=False),
    sa.Column('toDate', sa.DateTime(), nullable=False),
    sa.Column('prefixFrom', sa.DateTime(), nullable=True),
    sa.Column('prefixTo', sa.DateTime(), nullable=True),
    sa.Column('suffixFrom', sa.DateTime(), nullable=True),
    sa.Column('suffixTo', sa.DateTime(), nullable=True),
    sa.Column('earnedLeaveAvailed', sa.Integer(), nullable=False),
    sa.Column('natureOfTravel', sa.String(), nullable=False),
    sa.Column('placeToVisit', sa.String(), nullable=False),
    sa.Column('totalEstimatedFare', sa.Integer(), nullable=False),
    sa.Column('advanceRequired', sa.Boolean(), nullable=False),
    sa.Column('encashmentAvailed', sa.Boolean(), nullable=False),
    sa.Column('encashmentNoOfDays', sa.Integer(), nullable=False),
    sa.Column('stageRedirect', sa.Integer(), nullable=True),
    sa.Column('stageCurrent', sa.Integer(), nullable=False),
    sa.Column('fillDate', sa.DateTime(), nullable=False),
    sa.Column('hodDate', sa.DateTime(), nullable=True),
    sa.Column('estabDate', sa.DateTime(), nullable=True),
    sa.Column('accountsDate', sa.DateTime(), nullable=True),
    sa.Column('auditDate', sa.DateTime(), nullable=True),
    sa.Column('registrarDate', sa.DateTime(), nullable=True),
    sa.Column('deanDate', sa.DateTime(), nullable=True),
    sa.Column('lastForwardDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ltcId', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('handlerId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handlerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ltcId'], ['ltc_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expected_journey_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ltcId', sa.Integer(), nullable=False),
    sa.Column('departureFrom', sa.String(), nullable=False),
    sa.Column('arrivalTo', sa.String(), nullable=False),
    sa.Column('modeOfTravel', sa.String(), nullable=False),
    sa.Column('noOfFares', sa.Integer(), nullable=False),
    sa.Column('singleFare', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ltcId'], ['ltc_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_involved_ltc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ltcId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('back', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('fromPlace', sa.String(), nullable=False),
    sa.Column('toPlace', sa.String(), nullable=False),
    sa.Column('modeOfTravel', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ltcId'], ['ltc_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ta_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('ltcId', sa.Integer(), nullable=False),
    sa.Column('stageRedirect', sa.Integer(), nullable=True),
    sa.Column('stageCurrent', sa.Integer(), nullable=False),
    sa.Column('fillDate', sa.DateTime(), nullable=True),
    sa.Column('lastForwardDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ltcId'], ['ltc_infos.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taId', sa.Integer(), nullable=False),
    sa.Column('departureDate', sa.DateTime(), nullable=False),
    sa.Column('departureFrom', sa.String(), nullable=False),
    sa.Column('arrivalDate', sa.DateTime(), nullable=False),
    sa.Column('arrivalTo', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('modeOfTravel', sa.String(), nullable=False),
    sa.Column('classOfTravel', sa.String(), nullable=False),
    sa.Column('noOfFares', sa.Integer(), nullable=False),
    sa.Column('totalFare', sa.Integer(), nullable=False),
    sa.Column('ticketNo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['taId'], ['ta_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ltcFormId', sa.Integer(), nullable=True),
    sa.Column('taFormId', sa.Integer(), nullable=True),
    sa.Column('filePath', sa.String(), nullable=False),
    sa.CheckConstraint('"ltcFormId" IS NULL OR "taFormId" IS NULL', name='either_ltc_or_ta'),
    sa.ForeignKeyConstraint(['ltcFormId'], ['ltc_infos.id'], ),
    sa.ForeignKeyConstraint(['taFormId'], ['ta_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ta_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taId', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('handlerId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handlerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taId'], ['ta_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ta_comments')
    op.drop_table('receipts')
    op.drop_table('journey_details')
    op.drop_table('ta_infos')
    op.drop_table('people_involved_ltc')
    op.drop_table('expected_journey_details')
    op.drop_table('comments')
    op.drop_table('notifications')
    op.drop_table('ltc_infos')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
